# postgres conf

postgres:
  database: animeta_users
  user: postgres
  password: '123'
  host: localhost
  port: 5432
admin_user:
  username: admin
  password: adminadmin
jwt:
  private_key: '-----BEGIN RSA PRIVATE KEY-----\nMIIBOgIBAAJBAI6g6XgnStpyM6ffWI0vBnfOqTFWYaXdUgHeqUq1h7MgYIek5/5j\nCtU8kBNTEo8QchWZt8khbBkBdkWYkqiErKMCAwEAAQJAEDhSdLybMZ59K2El8+Be\nLu/Mo/S75B34Pogw3nMofIFNTKHn9+iWvQkgweMdIL302fwVPWS+YrK/yQqWBtjy\noQIhANhmipKuo2p/jhwstZApaeQo6cyltJIvtBTWNXpiMsIRAiEAqLp2VRyeY5W/\nBA+zWsOFuynmC05/t1drUOLjfMxQj3MCIQDV0lxSG2U1MdxFUpgEXidXXmXF5GXL\nnH8fp5kn2Ce3QQIgVH8si2sNlumDA1GpjCambhiJb9gb9YD96T/2lKTtIykCIC2P\nsd05bAQ5xPXM2ZuGekMjo56829m3ZUtA/F7T7G+5\n-----END RSA PRIVATE KEY-----'
  public_key:
    '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn6L3RWKPbJZS1CMdLw6K
Cc/82VBLhliFIsZoTw9wkNzWRhzDzoXY6jg7XkaaENdxzDsncAGFCAub3GgKoSeF
pzy7K01H6OksQyP68wXJgpm3CRFfHLOYICtKxbnEufsRVlX9Cd3/BHbhhWrLpiZm
0KbP0K0zpuEyrtOWCSHy/8Mq8gJ4T9UPQNeK5MndeqX+GQbMOrxWxNnwGGtJI+jl
iVX4qEUMD1ozi85aYyfCQzFKsX7lvKtAs6gggDIUYYB+/3a3+UvXIdzbG+Q8J2os
QrZ19uscfGKpwYOilY/mQKiEOUiOOGEcYy6Uaxsyq24gaBiVVWQDvy/lrhQ7BHbb
wQIDAQAB
-----END PUBLIC KEY-----'
